books/urls.py
from django.urls import path
from . import controller


urlpatterns = (
    path('', controller.list, name='list'),
    path('book/<int:pk>/', controller.book, name='book'),
)

mcv/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('books.urls', 'book'), namespace="book"))
]

books/models.py
from django.db import models


class Book(models.Model):
    name = models.CharField(max_length=300)
    writer = models.CharField(max_length=300)

    @staticmethod
    def get_all_books():
        return Book.objects.all()

    @staticmethod
    def get_book(pk):
        return Book.objects.get(pk=pk)

books/controller.py
from django.shortcuts import render
from .models import Book


def list(requests):
    '''Obtener todos los libros'''

    book_list = Book.get_all_books()  # acceso a los datos

    return render(requests, 'list.html', locals())  # definición de la vista (template) a mostrar


def book(requests, pk):
    '''Obtener la información del libro con pk definido'''

    book_obj = Book.get_book(pk=pk)  # acceso a los datos

    return render(requests, 'book.html', locals())  # definición de la vista (template) a mostrar

books/templates/book.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ book_obj.name }}</title>
</head>
<body>
    <h1>Nombre: {{ book_obj.name }}</h1>
    <p>Escritor: {{ book_obj.writer }}</p>
    <a href="/">Volver</a>
</body>
</html>

books/templates/list.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Lista de libros</title>
</head>
<body>
  <h1>Todos los libros</h1>
  <ol>
  {% for book_obj in book_list %}
    <li><a href="{% url 'book:book' book_obj.pk %}">{{ book_obj.name }}</a></li>  
  {% empty %}
    <li>Aún no hay libros en el sistema</li>
  {% endfor %}
  </ol>
</body>
</html>